In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras

from numpy import array
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from keras.layers import Dense, Activation
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model
from keras import regularizers, optimizers

from sklearn import preprocessing

In [3]:
initial_df = pd.read_csv(r"C:\Users\SANJANA\Desktop\RL\DOW_JONES_INTEGRATION\sp100_data_with_tickers.csv")

In [4]:
initial_df

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,2012-12-03,21.201786,21.235357,20.910713,20.935356,17.951883,364280000,AAPL
1,2012-12-04,20.778570,20.778570,20.433214,20.566071,17.635214,557068400,AAPL
2,2012-12-05,20.318214,20.330357,19.241785,19.242500,16.500261,1044638000,AAPL
3,2012-12-06,18.890715,19.761070,18.522499,19.544287,16.759045,1177212400,AAPL
4,2012-12-07,19.764286,19.828571,18.928572,19.044643,16.330601,787040800,AAPL
...,...,...,...,...,...,...,...,...
250892,2022-12-23,106.949997,108.739998,106.900002,108.680000,106.922302,11539400,XOM
250893,2022-12-27,109.269997,110.470001,108.830002,110.190002,108.407875,11962100,XOM
250894,2022-12-28,109.910004,110.000000,107.900002,108.379997,106.627151,10702100,XOM
250895,2022-12-29,107.989998,109.720001,107.989998,109.199997,107.433884,10534000,XOM
250896,2022-12-30,108.610001,110.500000,108.610001,110.300003,108.516098,11799600,XOM

In [5]:
import pandas as pd

df = pd.read_csv(r"C:\Users\SANJANA\Desktop\RL\DOW_JONES_INTEGRATION\sp100_data_with_tickers.csv")

df['date'] = pd.to_datetime(df['Date'])

df.set_index('date', inplace=True)
pivot_df = df.pivot(columns='Ticker', values='Close')
pivot_df = pivot_df.fillna(value=pd.np.nan)
pivot_df = pivot_df.bfill()

C:\Users\SANJANA\AppData\Local\Temp\ipykernel_19088\1773783130.py:9: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  pivot_df = pivot_df.fillna(value=pd.np.nan)

In [6]:
pivot_df

Ticker,AAPL,ABBV,ABT,ACN,ADBE,AIG,AMD,AMGN,AMT,AMZN,...,UNH,UNP,UPS,USB,V,VZ,WBA,WFC,WMT,XOM
date,,,,,,,,,,,,,,,,,,,,,
2012-12-03,20.935356,35.119999,30.846342,67.830002,34.700001,33.119999,2.360000,88.400002,74.879997,12.516500,...,53.889999,60.715000,72.269997,32.049999,37.160000,44.099998,34.279999,32.750000,71.339996,87.610001
2012-12-04,20.566071,35.119999,30.894321,68.610001,35.299999,33.320000,2.260000,88.330002,74.830002,12.624500,...,53.540001,61.185001,73.040001,31.430000,36.897499,43.669998,34.270000,32.740002,72.120003,87.190002
2012-12-05,19.242500,35.119999,30.966291,69.599998,35.400002,33.779999,2.290000,89.010002,74.610001,12.698000,...,53.840000,61.430000,73.500000,31.760000,37.014999,44.099998,35.570000,32.980000,71.650002,87.730003
2012-12-06,19.544287,35.119999,30.985483,69.800003,35.139999,33.259998,2.340000,88.540001,74.980003,12.668500,...,53.650002,61.564999,72.930000,31.809999,37.117500,44.450001,35.849998,33.139999,71.589996,88.000000
2012-12-07,19.044643,35.119999,31.441294,69.480003,35.480000,34.130001,2.360000,88.320000,75.449997,12.663500,...,53.869999,61.974998,73.169998,32.020000,37.137501,44.410000,36.099998,33.230000,72.290001,88.599998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,131.860001,163.100006,108.180000,266.089996,338.450012,63.160000,64.519997,263.920013,212.449997,85.250000,...,531.309998,209.910004,177.009995,43.200001,205.830002,38.410000,38.630001,40.980000,143.770004,108.680000
2022-12-27,130.029999,162.990005,108.570000,265.309998,335.089996,63.330002,63.270000,263.390015,210.899994,83.040001,...,531.989990,210.320007,176.929993,43.650002,206.289993,39.250000,38.310001,41.040001,143.809998,110.190002
2022-12-28,126.040001,162.229996,107.830002,263.119995,328.329987,62.889999,62.570000,261.420013,210.100006,81.820000,...,528.450012,206.869995,173.610001,43.349998,204.990005,38.810001,37.580002,41.119999,141.289993,108.379997
2022-12-29,129.610001,162.559998,110.309998,268.380005,337.579987,63.630001,64.820000,263.160004,215.740005,84.180000,...,529.880005,209.220001,175.750000,43.570000,208.059998,39.259998,37.470001,41.330002,142.149994,109.199997
2022-12-30,129.929993,161.610001,109.790001,266.839996,336.529999,63.240002,64.769997,262.640015,211.860001,84.000000,...,530.179993,207.070007,173.839996,43.610001,207.759995,39.400002,37.360001,41.290001,141.789993,110.300003

In [7]:
nan_counts = pivot_df.isna().sum()
print(nan_counts)

Ticker
AAPL    0
ABBV    0
ABT     0
ACN     0
ADBE    0
       ..
VZ      0
WBA     0
WFC     0
WMT     0
XOM     0
Length: 100, dtype: int64

In [8]:
pivot_df.shape

(2538, 100)

In [9]:
pivot_df.head()

Ticker,AAPL,ABBV,ABT,ACN,ADBE,AIG,AMD,AMGN,AMT,AMZN,...,UNH,UNP,UPS,USB,V,VZ,WBA,WFC,WMT,XOM
date,,,,,,,,,,,,,,,,,,,,,
2012-12-03,20.935356,35.119999,30.846342,67.830002,34.700001,33.119999,2.36,88.400002,74.879997,12.5165,...,53.889999,60.715000,72.269997,32.049999,37.160000,44.099998,34.279999,32.750000,71.339996,87.610001
2012-12-04,20.566071,35.119999,30.894321,68.610001,35.299999,33.320000,2.26,88.330002,74.830002,12.6245,...,53.540001,61.185001,73.040001,31.430000,36.897499,43.669998,34.270000,32.740002,72.120003,87.190002
2012-12-05,19.242500,35.119999,30.966291,69.599998,35.400002,33.779999,2.29,89.010002,74.610001,12.6980,...,53.840000,61.430000,73.500000,31.760000,37.014999,44.099998,35.570000,32.980000,71.650002,87.730003
2012-12-06,19.544287,35.119999,30.985483,69.800003,35.139999,33.259998,2.34,88.540001,74.980003,12.6685,...,53.650002,61.564999,72.930000,31.809999,37.117500,44.450001,35.849998,33.139999,71.589996,88.000000
2012-12-07,19.044643,35.119999,31.441294,69.480003,35.480000,34.130001,2.36,88.320000,75.449997,12.6635,...,53.869999,61.974998,73.169998,32.020000,37.137501,44.410000,36.099998,33.230000,72.290001,88.599998

In [10]:
df_pct_change = pivot_df.pct_change(1).astype(float)
df_pct_change = df_pct_change.replace([np.inf, -np.inf], np.nan)
df_pct_change = df_pct_change.fillna(method='ffill')

In [11]:
df_pct_change.head()

Ticker,AAPL,ABBV,ABT,ACN,ADBE,AIG,AMD,AMGN,AMT,AMZN,...,UNH,UNP,UPS,USB,V,VZ,WBA,WFC,WMT,XOM
date,,,,,,,,,,,,,,,,,,,,,
2012-12-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-12-04,-0.017639,0.0,0.001555,0.011499,0.017291,0.006039,-0.042373,-0.000792,-0.000668,0.008629,...,-0.006495,0.007741,0.010655,-0.019345,-0.007064,-0.009751,-0.000292,-0.000305,0.010934,-0.004794
2012-12-05,-0.064357,0.0,0.002330,0.014429,0.002833,0.013805,0.013274,0.007698,-0.002940,0.005822,...,0.005603,0.004004,0.006298,0.010500,0.003185,0.009847,0.037934,0.007330,-0.006517,0.006193
2012-12-06,0.015683,0.0,0.000620,0.002874,-0.007345,-0.015394,0.021834,-0.005280,0.004959,-0.002323,...,-0.003529,0.002198,-0.007755,0.001574,0.002769,0.007937,0.007872,0.004851,-0.000837,0.003078
2012-12-07,-0.025565,0.0,0.014710,-0.004585,0.009676,0.026158,0.008547,-0.002485,0.006268,-0.000395,...,0.004101,0.006660,0.003291,0.006602,0.000539,-0.000900,0.006974,0.002716,0.009778,0.006818

In [12]:
# the percentage change function will make the first two rows equal to nan
df_pct_change = df_pct_change.tail(len(df_pct_change) - 1)

In [13]:
df_pct_change.head()

Ticker,AAPL,ABBV,ABT,ACN,ADBE,AIG,AMD,AMGN,AMT,AMZN,...,UNH,UNP,UPS,USB,V,VZ,WBA,WFC,WMT,XOM
date,,,,,,,,,,,,,,,,,,,,,
2012-12-04,-0.017639,0.0,0.001555,0.011499,0.017291,0.006039,-0.042373,-0.000792,-0.000668,0.008629,...,-0.006495,0.007741,0.010655,-0.019345,-0.007064,-0.009751,-0.000292,-0.000305,0.010934,-0.004794
2012-12-05,-0.064357,0.0,0.002330,0.014429,0.002833,0.013805,0.013274,0.007698,-0.002940,0.005822,...,0.005603,0.004004,0.006298,0.010500,0.003185,0.009847,0.037934,0.007330,-0.006517,0.006193
2012-12-06,0.015683,0.0,0.000620,0.002874,-0.007345,-0.015394,0.021834,-0.005280,0.004959,-0.002323,...,-0.003529,0.002198,-0.007755,0.001574,0.002769,0.007937,0.007872,0.004851,-0.000837,0.003078
2012-12-07,-0.025565,0.0,0.014710,-0.004585,0.009676,0.026158,0.008547,-0.002485,0.006268,-0.000395,...,0.004101,0.006660,0.003291,0.006602,0.000539,-0.000900,0.006974,0.002716,0.009778,0.006818
2012-12-10,-0.006432,0.0,-0.003052,0.000432,0.007610,-0.022561,-0.016949,0.016078,-0.004374,-0.021716,...,0.005940,0.010327,0.006970,-0.003748,0.000740,-0.008557,0.006925,-0.005417,-0.001937,-0.002144

In [14]:
df_pct_change.shape

(2537, 100)

In [15]:
# remove columns where there is no change over a longer time period
df_pct_change = df_pct_change[df_pct_change.columns[((df_pct_change == 0).mean() <= 0.05)]]

In [16]:
df_pct_change.shape

(2537, 97)

In [17]:
#define autoencoder


def defineAutoencoder(num_stock, encoding_dim = 5, verbose=0):
    
    """
    Function for fitting an Autoencoder
    """

    # connect all layers
    input = Input(shape=(num_stock,))

    encoded = Dense(encoding_dim, kernel_regularizer=regularizers.l2(0.00001),name ='Encoder_Input')(input)

    decoded = Dense(num_stock, kernel_regularizer=regularizers.l2(0.00001), name ='Decoder_Input')(encoded)
    decoded = Activation("linear", name='Decoder_Activation_function')(decoded)

    # construct and compile AE model
    autoencoder = Model(inputs=input, outputs=decoded)
    adam = optimizers.Adam(lr=0.0005)
    autoencoder.compile(optimizer=adam, loss='mean_squared_error')
    if verbose!= 0:
        autoencoder.summary()

    return autoencoder

In [18]:
def getReconstructionErrorsDF(df_pct_change, reconstructed_data):
    
    """
    Function for calculating the reconstruction Errors
    """
    array = []
    stocks_ranked = []
    num_columns = reconstructed_data.shape[1]
    for i in range(0, num_columns):
        diff = np.linalg.norm((df_pct_change.iloc[:, i] - reconstructed_data[:, i]))  # 2 norm difference
        array.append(float(diff))

    ranking = np.array(array).argsort()
    r = 1
    for stock_index in ranking:
        stocks_ranked.append([ r
                              ,stock_index
                              ,df_pct_change.iloc[:, stock_index].name
                              ,array[stock_index]
                              ])
        r = r + 1

    columns = ['ranking','stock_index', 'stock_name' ,'recreation_error']
    df = pd.DataFrame(stocks_ranked, columns=columns)
    df = df.set_index('stock_name')
    return df

In [19]:
# define the input parameters
hidden_layers = 5
batch_size = 500
epochs = 500
stock_selection_number = 20
num_stock = df_pct_change.shape[1]
verbose = 1

In [20]:
# Normalize the data
df_scaler = preprocessing.MinMaxScaler()
df_pct_change_normalised = df_scaler.fit_transform(df_pct_change)

In [21]:
# define autoencoder
print('-' * 25 + 'Define autoencoder model')
num_stock = len(df_pct_change.columns)
autoencoder = defineAutoencoder(num_stock=num_stock, encoding_dim=hidden_layers, verbose=verbose)

-------------------------Define autoencoder model
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 97)]              0

 Encoder_Input (Dense)       (None, 5)                 490

 Decoder_Input (Dense)       (None, 97)                582

 Decoder_Activation_function  (None, 97)               0
  (Activation)

=================================================================
Total params: 1,072
Trainable params: 1,072
Non-trainable params: 0
_________________________________________________________________

C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)

In [22]:
# train autoencoder
print('-' * 25 + 'Train autoencoder model')
autoencoder.fit(df_pct_change_normalised, df_pct_change_normalised, shuffle=False, epochs=epochs,
                batch_size=batch_size,
                verbose=verbose)

-------------------------Train autoencoder model
Epoch 1/500
6/6 [==============================] - 1s 3ms/step - loss: 0.3803
Epoch 2/500
6/6 [==============================] - 0s 4ms/step - loss: 0.3415
Epoch 3/500
6/6 [==============================] - 0s 4ms/step - loss: 0.3105
Epoch 4/500
6/6 [==============================] - 0s 2ms/step - loss: 0.2853
Epoch 5/500
6/6 [==============================] - 0s 3ms/step - loss: 0.2647
Epoch 6/500
6/6 [==============================] - 0s 4ms/step - loss: 0.2478
Epoch 7/500
6/6 [==============================] - 0s 3ms/step - loss: 0.2333
Epoch 8/500
6/6 [==============================] - 0s 3ms/step - loss: 0.2206
Epoch 9/500
6/6 [==============================] - 0s 3ms/step - loss: 0.2091
Epoch 10/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1984
Epoch 11/500
6/6 [==============================] - 0s 2ms/step - loss: 0.1883
Epoch 12/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1785
Epoch 13/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1689
Epoch 14/500
6/6 [==============================] - 0s 4ms/step - loss: 0.1596
Epoch 15/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1503
Epoch 16/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1412
Epoch 17/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1322
Epoch 18/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1235
Epoch 19/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1150
Epoch 20/500
6/6 [==============================] - 0s 3ms/step - loss: 0.1068
Epoch 21/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0989
Epoch 22/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0915
Epoch 23/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0844
Epoch 24/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0777
Epoch 25/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0714
Epoch 26/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0655
Epoch 27/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0601
Epoch 28/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0550
Epoch 29/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0504
Epoch 30/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0461
Epoch 31/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0421
Epoch 32/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0385
Epoch 33/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0352
Epoch 34/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0322
Epoch 35/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0294
Epoch 36/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0269
Epoch 37/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0246
Epoch 38/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0225
Epoch 39/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0207
Epoch 40/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0190
Epoch 41/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0174
Epoch 42/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0161
Epoch 43/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0148
Epoch 44/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0137
Epoch 45/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0126
Epoch 46/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0117
Epoch 47/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0109
Epoch 48/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0101
Epoch 49/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0094
Epoch 50/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0088
Epoch 51/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0083
Epoch 52/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0077
Epoch 53/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0073
Epoch 54/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0069
Epoch 55/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0065
Epoch 56/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0061
Epoch 57/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0058
Epoch 58/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0055
Epoch 59/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0053
Epoch 60/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0050
Epoch 61/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0048
Epoch 62/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0046
Epoch 63/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0044
Epoch 64/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0043
Epoch 65/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0041
Epoch 66/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0040
Epoch 67/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0039
Epoch 68/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0038
Epoch 69/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0037
Epoch 70/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0036
Epoch 71/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0035
Epoch 72/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0034
Epoch 73/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0034
Epoch 74/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0033
Epoch 75/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0032
Epoch 76/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 77/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0031
Epoch 78/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 79/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 80/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0030
Epoch 81/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0030
Epoch 82/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0030
Epoch 83/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0029
Epoch 84/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0029
Epoch 85/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0029
Epoch 86/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0029
Epoch 87/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0029
Epoch 88/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 89/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0028
Epoch 90/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 91/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 92/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 93/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 94/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 95/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 96/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0028
Epoch 97/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 98/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 99/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 100/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 101/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 102/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 103/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 104/500

6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 105/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 106/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 107/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 108/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 109/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 110/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 111/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 112/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 113/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 114/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 115/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 116/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 117/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 118/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 119/500
6/6 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 120/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 121/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 122/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 123/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 124/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 125/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 126/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 127/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 128/500
6/6 [==============================] - 0s 5ms/step - loss: 0.0027
Epoch 129/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 130/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 131/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 132/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 133/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 134/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 135/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 136/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 137/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 138/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 139/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 140/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 141/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 142/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 143/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 144/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 145/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 146/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 147/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 148/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 149/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 150/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 151/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 152/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 153/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 154/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 155/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 156/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 157/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 158/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0027
Epoch 159/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0027
Epoch 160/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 161/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 162/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 163/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 164/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 165/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 166/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 167/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 168/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 169/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 170/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 171/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 172/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 173/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 174/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 175/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 176/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 177/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 178/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 179/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 180/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 181/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 182/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 183/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 184/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 185/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 186/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 187/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 188/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 189/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 190/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 191/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 192/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 193/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 194/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 195/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 196/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 197/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 198/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 199/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 200/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 201/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 202/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 203/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 204/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 205/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 206/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 207/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 208/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 209/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 210/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 211/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 212/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 213/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 214/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 215/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 216/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 217/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 218/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 219/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 220/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 221/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 222/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 223/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 224/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 225/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 226/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 227/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 228/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 229/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 230/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 231/500
6/6 [==============================] - 0s 5ms/step - loss: 0.0026
Epoch 232/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 233/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 234/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 235/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 236/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 237/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 238/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 239/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 240/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 241/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 242/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 243/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 244/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 245/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 246/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 247/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 248/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 249/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 250/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 251/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 252/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 253/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 254/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 255/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 256/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 257/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 258/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 259/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 260/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 261/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 262/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 263/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 264/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0026
Epoch 265/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 266/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 267/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0026
Epoch 268/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 269/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 270/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 271/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 272/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 273/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 274/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 275/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 276/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 277/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 278/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 279/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 280/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 281/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 282/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 283/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 284/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 285/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 286/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 287/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 288/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 289/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 290/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 291/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 292/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 293/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 294/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 295/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 296/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 297/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 298/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 299/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 300/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 301/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 302/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 303/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 304/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 305/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 306/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 307/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 308/500

6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 309/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 310/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 311/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 312/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 313/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 314/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 315/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 316/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 317/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 318/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 319/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 320/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 321/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 322/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 323/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 324/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 325/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 326/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 327/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 328/500
6/6 [==============================] - 0s 6ms/step - loss: 0.0025
Epoch 329/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 330/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 331/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 332/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 333/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 334/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 335/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 336/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 337/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 338/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 339/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 340/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 341/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 342/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 343/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 344/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 345/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 346/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 347/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 348/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 349/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 350/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 351/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 352/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 353/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 354/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 355/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 356/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 357/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 358/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 359/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 360/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 361/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 362/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 363/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 364/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 365/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 366/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 367/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 368/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 369/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 370/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 371/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 372/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 373/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 374/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 375/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 376/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 377/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 378/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 379/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 380/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 381/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 382/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 383/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 384/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 385/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0025
Epoch 386/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 387/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0025
Epoch 388/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 389/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 390/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 391/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 392/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 393/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 394/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 395/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 396/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 397/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 398/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 399/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 400/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 401/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 402/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 403/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 404/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 405/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 406/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 407/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 408/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 409/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 410/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 411/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 412/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 413/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 414/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 415/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 416/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 417/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 418/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 419/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 420/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 421/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 422/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 423/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 424/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 425/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 426/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 427/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 428/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 429/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 430/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 431/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 432/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 433/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 434/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 435/500
6/6 [==============================] - 0s 5ms/step - loss: 0.0024
Epoch 436/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 437/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 438/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 439/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 440/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 441/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 442/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 443/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 444/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 445/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 446/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 447/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 448/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 449/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 450/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 451/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 452/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 453/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 454/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 455/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 456/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 457/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 458/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 459/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 460/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 461/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 462/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 463/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 464/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 465/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 466/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 467/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 468/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 469/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 470/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 471/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 472/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 473/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 474/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 475/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 476/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 477/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 478/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 479/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 480/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 481/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 482/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 483/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 484/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 485/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 486/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 487/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 488/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 489/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 490/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 491/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 492/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 493/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 494/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 495/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 496/500
6/6 [==============================] - 0s 3ms/step - loss: 0.0024
Epoch 497/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 498/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 499/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024
Epoch 500/500
6/6 [==============================] - 0s 4ms/step - loss: 0.0024

In [22]:
reconstruct = autoencoder.predict(df_pct_change_normalised)

80/80 [==============================] - 1s 3ms/step

In [23]:
reconstruct_real = df_scaler.inverse_transform(reconstruct)
df_reconstruct_real = pd.DataFrame(data=reconstruct_real, columns=df_pct_change.columns)
df_recreation_error = getReconstructionErrorsDF(df_pct_change=df_pct_change,
                                                reconstructed_data=reconstruct_real)

In [24]:
df_recreation_error

            ranking  stock_index  recreation_error
stock_name
CMCSA             1           22          2.411590
LIN               2           51          2.465913
SO                3           79          3.398667
KO                4           50          3.534893
PFE               5           72          3.592201
...             ...          ...               ...
LOW              93           54         14.151269
TSLA             94           85         14.298415
TMUS             95           84         14.851661
AMD              96            6         15.388615
NFLX             97           67         18.972750

[97 rows x 3 columns]

In [25]:
filtered_stocks = df_recreation_error.head(stock_selection_number).index

In [26]:
stock_selection_number

20

In [27]:
filtered_stocks

Index(['CMCSA', 'LIN', 'SO', 'KO', 'PFE', 'ACN', 'AMGN', 'VZ', 'MA', 'DUK',
       'COST', 'USB', 'ABT', 'AXP', 'DHR', 'UPS', 'MCD', 'JNJ', 'TXN', 'V'],
      dtype='object', name='stock_name')

In [28]:
selected_stocks = filtered_stocks
print(selected_stocks)

Index(['CMCSA', 'LIN', 'SO', 'KO', 'PFE', 'ACN', 'AMGN', 'VZ', 'MA', 'DUK',
       'COST', 'USB', 'ABT', 'AXP', 'DHR', 'UPS', 'MCD', 'JNJ', 'TXN', 'V'],
      dtype='object', name='stock_name')

In [29]:
%store selected_stocks

Stored 'selected_stocks' (Index)

In [30]:
initial_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,2012-12-03,21.201786,21.235357,20.910713,20.935356,17.951883,364280000,AAPL
1,2012-12-04,20.778570,20.778570,20.433214,20.566071,17.635214,557068400,AAPL
2,2012-12-05,20.318214,20.330357,19.241785,19.242500,16.500261,1044638000,AAPL
3,2012-12-06,18.890715,19.761070,18.522499,19.544287,16.759045,1177212400,AAPL
4,2012-12-07,19.764286,19.828571,18.928572,19.044643,16.330601,787040800,AAPL

In [31]:
initial_df = initial_df.drop('Adj Close', axis=1)

In [32]:
initial_df['Ticker'].unique()

array(['AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'AIG', 'AMD', 'AMGN', 'AMT',
       'AMZN', 'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY',
       'C', 'CAT', 'CHTR', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM',
       'CSCO', 'CVS', 'CVX', 'DHR', 'DIS', 'DOW', 'DUK', 'EMR', 'EXC',
       'F', 'FDX', 'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD',
       'HON', 'IBM', 'INTC', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LLY',
       'LMT', 'LOW', 'MA', 'MCD', 'MDLZ', 'MDT', 'MET', 'META', 'MMM',
       'MO', 'MRK', 'MS', 'MSFT', 'NEE', 'NFLX', 'NKE', 'NVDA', 'ORCL',
       'PEP', 'PFE', 'PG', 'PM', 'PYPL', 'QCOM', 'RTX', 'SBUX', 'SCHW',
       'SO', 'SPG', 'T', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH',
       'UNP', 'UPS', 'USB', 'V', 'VZ', 'WBA', 'WFC', 'WMT', 'XOM'],
      dtype=object)

In [33]:
data = initial_df[initial_df['Ticker'].isin(selected_stocks)]

In [34]:
data.Ticker.unique()

array(['ABT', 'ACN', 'AMGN', 'AXP', 'CMCSA', 'COST', 'DHR', 'DUK', 'JNJ',
       'KO', 'LIN', 'MA', 'MCD', 'PFE', 'SO', 'TXN', 'UPS', 'USB', 'V',
       'VZ'], dtype=object)

In [35]:
import ta
from ta import add_all_ta_features
from ta.utils import dropna
from finrl.preprocessing.data import data_split
from finrl.preprocessing.preprocessors import FeatureEngineer

In [36]:
# Define a Function for adding technical indicators

def add_features(data, feature_list, short_names):

    data_col_names = list(data.columns)
    filter_names = data_col_names + feature_list
    col_rename = data_col_names +  short_names
    
    # Add technical indicators using the ta Library
    data = add_all_ta_features(data, open="Open", high="High", 
    low="Low", close="Close", volume="Volume") 
    
    # Filter the Indicators with the required features
    data = data[filter_names]
    data.columns = col_rename # rename the columns to use shortened indicator names
    data = data.dropna()
    
    return data


# List of Features to add
feature_list= ['volatility_atr','volatility_bbw','volume_obv','volume_cmf',
               'trend_macd', 'trend_adx', 'trend_sma_fast', 
               'trend_ema_fast', 'trend_cci', 'momentum_rsi']

# Short names of the features
short_names = ['atr', 'bbw','obv','cmf','macd', 'adx', 'sma', 'ema', 'cci', 'rsi']

In [37]:
# Add Indicators to our dataset
data_with_features = data.copy()

data_with_features = add_features(data_with_features, feature_list, short_names)

C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\volatility.py:50: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  atr[self._window - 1] = true_range[0: self._window].mean()
C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:730: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  self._trs[0] = diff_directional_movement.dropna()[
C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:748: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  self._dip[0] = pos.dropna()[0: self._window].sum()
C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:760: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  self._din[0] = neg.dropna()[0: self._window].sum()
C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:780: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
C:\Users\SANJANA\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:785: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

In [38]:
data_with_features.head()

,Date,Open,High,Low,Close,Volume,Ticker,atr,bbw,obv,cmf,macd,adx,sma,ema,cci,rsi
5081,2013-01-09,33.660000,33.709999,33.090000,33.570000,11313000,ABT,0.572095,10.596769,124575637,0.218518,0.572098,0.000000,32.209641,32.511873,150.824650,75.686748
5082,2013-01-10,33.700001,33.939999,33.660000,33.849998,9668400,ABT,0.551886,11.779118,134244037,0.200118,0.636465,0.000000,32.389575,32.717739,149.713638,77.629999
5083,2013-01-11,33.880001,33.880001,33.320000,33.369999,8554700,ABT,0.552697,12.248703,125689337,0.229468,0.641352,47.362556,32.552699,32.818086,107.038354,67.648147
5084,2013-01-14,33.480000,33.570000,33.139999,33.360001,6848700,ABT,0.540428,12.453237,118840637,0.247462,0.637074,47.049640,32.731384,32.901458,82.864134,67.453585
5085,2013-01-15,33.189999,33.360001,32.970001,33.020000,12815200,ABT,0.525385,12.356631,106025437,0.198924,0.599340,46.204128,32.882134,32.919695,58.851918,61.025928

In [39]:
data_with_features = data_with_features.rename(columns={'Date': 'date'})

In [40]:
#adding covariance matrix


def add_cov_matrix(df):
    """
    Function to add Coveriance Matrices as part of the defined states
    """
    # Sort the data and index by date and tic
    df=df.sort_values(['date','Ticker'],ignore_index=True) 
    df.index = df.date.factorize()[0]
    
    cov_list = [] # create empty list for storing coveriance matrices at each time step
    
    # look back for constructing the coveriance matrix is one year
    lookback=252
    for i in range(lookback,len(df.index.unique())):
        data_lookback = df.loc[i-lookback:i,:]
        price_lookback=data_lookback.pivot_table(index = 'date',columns = 'Ticker', values = 'Close')
        return_lookback = price_lookback.pct_change().dropna()
        covs = return_lookback.cov().values 
        covs = covs#/covs.max()
        cov_list.append(covs)
        
    df_cov = pd.DataFrame({'date':df.date.unique()[lookback:],'cov_list':cov_list})
    df = df.merge(df_cov, on='date')
    df = df.sort_values(['date','Ticker']).reset_index(drop=True)
    
    return df

In [41]:
# Add Covariance Matrices to our dataset
data_with_features_covs = data_with_features.copy()
data_with_features_covs = add_cov_matrix(data_with_features_covs)

In [42]:
data_with_features_covs

,date,Open,High,Low,Close,Volume,Ticker,atr,bbw,obv,cmf,macd,adx,sma,ema,cci,rsi,cov_list
0,2013-12-03,37.950001,37.980000,37.259998,37.599998,7798700,ABT,0.569723,3.394696,196992437,0.055634,0.417395,33.540247,38.139166,37.997197,-80.958286,50.803169,"[[0.0001457882820790863, 5.427183543955608e-05..."
1,2013-12-03,76.330002,77.239998,76.029999,77.089996,2138700,ACN,1.113311,6.965746,993674137,0.042599,0.760190,27.899115,77.710000,77.143621,-5.542048,55.330879,"[[0.0001457882820790863, 5.427183543955608e-05..."
2,2013-12-03,114.440002,114.470001,112.959999,113.449997,2582300,AMGN,2.018363,4.295693,1358836137,-0.084453,-0.122541,12.489529,114.230000,114.040799,-25.742533,47.289749,"[[0.0001457882820790863, 5.427183543955608e-05..."
3,2013-12-03,84.889999,85.330002,84.199997,84.610001,3546100,AXP,1.026293,7.621025,1739265537,0.077751,1.431316,30.878730,84.051666,84.179818,78.967733,63.058139,"[[0.0001457882820790863, 5.427183543955608e-05..."
4,2013-12-03,24.635000,24.674999,24.120001,24.385000,22124600,CMCSA,0.465067,8.658425,2354191937,-0.007326,0.336446,19.818174,24.317500,24.405680,42.366350,55.607095,"[[0.0001457882820790863, 5.427183543955608e-05..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45715,2022-12-30,163.690002,165.389999,162.210007,165.220001,3249000,TXN,4.097134,12.754489,11669263576,0.115737,-2.220366,17.753348,166.841667,166.840224,-81.862370,43.187099,"[[0.00028049585292047607, 0.000245791874911675..."
45716,2022-12-30,174.259995,174.850006,171.889999,173.839996,1670900,UPS,3.982235,9.148620,11800827176,-0.161201,-0.836804,12.435549,177.100831,176.642102,-102.410003,44.217214,"[[0.00028049585292047607, 0.000245791874911675..."
45717,2022-12-30,43.400002,43.799999,43.279999,43.610001,5737900,USB,0.841648,7.495823,12543402976,0.053584,-0.043884,11.191549,42.925000,43.252141,34.514776,52.703524,"[[0.00028049585292047607, 0.000245791874911675..."
45718,2022-12-30,206.309998,208.039993,205.699997,207.759995,4159400,V,3.791076,6.862015,13777017176,-0.087997,-0.201309,9.991681,206.925001,207.348775,-38.306813,50.522009,"[[0.00028049585292047607, 0.000245791874911675..."
45719,2022-12-30,39.310001,39.689999,39.070000,39.400002,44007200,VZ,0.810376,8.448232,13333630776,0.098244,0.302003,15.578860,38.131667,38.455454,159.989685,62.322186,"[[0.00028049585292047607, 0.000245791874911675..."

In [43]:
import tensorflow as tf
import keras
import matplotlib.pyplot as plt

# lstm autoencoder recreate sequence
from numpy import array
from keras.models import Model, Sequential
from keras.layers import Input
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.utils import plot_model

from sklearn import preprocessing

In [44]:
# Get the list of all the features
features_list = list(data_with_features_covs.columns)[7:-1]

In [45]:
print(features_list)

['atr', 'bbw', 'obv', 'cmf', 'macd', 'adx', 'sma', 'ema', 'cci', 'rsi']

In [46]:
# construct a data frame of features
features_df = data_with_features_covs[features_list]
features_df.index = data_with_features_covs['date']
features_df.head()

,atr,bbw,obv,cmf,macd,adx,sma,ema,cci,rsi
date,,,,,,,,,,
2013-12-03,0.569723,3.394696,196992437,0.055634,0.417395,33.540247,38.139166,37.997197,-80.958286,50.803169
2013-12-03,1.113311,6.965746,993674137,0.042599,0.760190,27.899115,77.710000,77.143621,-5.542048,55.330879
2013-12-03,2.018363,4.295693,1358836137,-0.084453,-0.122541,12.489529,114.230000,114.040799,-25.742533,47.289749
2013-12-03,1.026293,7.621025,1739265537,0.077751,1.431316,30.878730,84.051666,84.179818,78.967733,63.058139
2013-12-03,0.465067,8.658425,2354191937,-0.007326,0.336446,19.818174,24.317500,24.405680,42.366350,55.607095

In [47]:
data_with_features_covs.shape

(45720, 18)

In [48]:
features_df.shape

(45720, 10)

In [49]:
features_array = np.array(features_df)

features_scaler = preprocessing.MinMaxScaler()
features_normalised = features_scaler.fit_transform(features_array)

In [50]:
# rescale the features array
features_normalised = features_normalised.reshape(-1,20,10)

In [51]:
features_normalised.shape

(2286, 20, 10)

In [52]:
# define model
model = Sequential()
model.add(LSTM(4, activation='relu', input_shape=(20,10)))
model.add(RepeatVector(20))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(10)))
model.compile(optimizer='adam', loss='mse')

In [53]:
# fit model
model.fit(features_normalised, features_normalised, epochs=100, verbose=1)

Epoch 1/100
72/72 [==============================] - 10s 49ms/step - loss: 0.0732
Epoch 2/100
72/72 [==============================] - 4s 49ms/step - loss: 0.0205
Epoch 3/100
72/72 [==============================] - 4s 50ms/step - loss: 0.0155
Epoch 4/100
72/72 [==============================] - 4s 53ms/step - loss: 0.0133
Epoch 5/100
72/72 [==============================] - 4s 50ms/step - loss: 0.0115
Epoch 6/100
72/72 [==============================] - 4s 51ms/step - loss: 0.0108
Epoch 7/100
72/72 [==============================] - 4s 53ms/step - loss: 0.0105
Epoch 8/100
72/72 [==============================] - 4s 59ms/step - loss: 0.0102
Epoch 9/100
72/72 [==============================] - 4s 52ms/step - loss: 0.0100
Epoch 10/100
72/72 [==============================] - 4s 58ms/step - loss: 0.0099
Epoch 11/100
72/72 [==============================] - 4s 53ms/step - loss: 0.0097
Epoch 12/100
72/72 [==============================] - 4s 58ms/step - loss: 0.0096
Epoch 13/100
72/72 [==============================] - 5s 65ms/step - loss: 0.0096
Epoch 14/100
72/72 [==============================] - 4s 55ms/step - loss: 0.0095
Epoch 15/100
72/72 [==============================] - 4s 54ms/step - loss: 0.0092
Epoch 16/100
72/72 [==============================] - 4s 52ms/step - loss: 0.0087
Epoch 17/100
72/72 [==============================] - 4s 62ms/step - loss: 0.0084
Epoch 18/100
72/72 [==============================] - 4s 57ms/step - loss: 0.0082
Epoch 19/100
72/72 [==============================] - 4s 59ms/step - loss: 0.0079
Epoch 20/100
72/72 [==============================] - 4s 50ms/step - loss: 0.0076
Epoch 21/100
72/72 [==============================] - 4s 55ms/step - loss: 0.0074
Epoch 22/100
72/72 [==============================] - 4s 52ms/step - loss: 0.0072
Epoch 23/100
72/72 [==============================] - 3s 43ms/step - loss: 0.0070
Epoch 24/100
72/72 [==============================] - 3s 44ms/step - loss: 0.0069
Epoch 25/100
72/72 [==============================] - 3s 48ms/step - loss: 0.0069
Epoch 26/100
72/72 [==============================] - 3s 44ms/step - loss: 0.0068
Epoch 27/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0068
Epoch 28/100
72/72 [==============================] - 3s 47ms/step - loss: 0.0067
Epoch 29/100
72/72 [==============================] - 3s 44ms/step - loss: 0.0067
Epoch 30/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0066
Epoch 31/100
72/72 [==============================] - 3s 43ms/step - loss: 0.0066
Epoch 32/100
72/72 [==============================] - 4s 55ms/step - loss: 0.0066
Epoch 33/100
72/72 [==============================] - 4s 57ms/step - loss: 0.0065
Epoch 34/100
72/72 [==============================] - 5s 63ms/step - loss: 0.0064
Epoch 35/100
72/72 [==============================] - 4s 48ms/step - loss: 0.0064
Epoch 36/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0063
Epoch 37/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0063
Epoch 38/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0063
Epoch 39/100
72/72 [==============================] - 4s 53ms/step - loss: 0.0062
Epoch 40/100
72/72 [==============================] - 4s 62ms/step - loss: 0.0062
Epoch 41/100
72/72 [==============================] - 4s 61ms/step - loss: 0.0062
Epoch 42/100
72/72 [==============================] - 4s 60ms/step - loss: 0.0062
Epoch 43/100
72/72 [==============================] - 4s 55ms/step - loss: 0.0062
Epoch 44/100
72/72 [==============================] - 4s 49ms/step - loss: 0.0062
Epoch 45/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0062
Epoch 46/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0061
Epoch 47/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0062
Epoch 48/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0061
Epoch 49/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0061
Epoch 50/100
72/72 [==============================] - 3s 45ms/step - loss: 0.0061
Epoch 51/100
72/72 [==============================] - 5s 63ms/step - loss: 0.0061
Epoch 52/100
72/72 [==============================] - 4s 55ms/step - loss: 0.0061
Epoch 53/100
72/72 [==============================] - 5s 65ms/step - loss: 0.0061
Epoch 54/100
72/72 [==============================] - 5s 69ms/step - loss: 0.0061
Epoch 55/100
72/72 [==============================] - 5s 67ms/step - loss: 0.0061
Epoch 56/100
72/72 [==============================] - 4s 59ms/step - loss: 0.0061
Epoch 57/100
72/72 [==============================] - 3s 46ms/step - loss: 0.0060
Epoch 58/100
72/72 [==============================] - 3s 48ms/step - loss: 0.0060
Epoch 59/100
72/72 [==============================] - 3s 48ms/step - loss: 0.0060
Epoch 60/100
72/72 [==============================] - 4s 51ms/step - loss: 0.0060
Epoch 61/100
72/72 [==============================] - 5s 67ms/step - loss: 0.0060
Epoch 62/100
72/72 [==============================] - 6s 90ms/step - loss: 0.0060
Epoch 63/100
72/72 [==============================] - 7s 101ms/step - loss: 0.0060
Epoch 64/100
72/72 [==============================] - 7s 98ms/step - loss: 0.0060
Epoch 65/100
72/72 [==============================] - 6s 79ms/step - loss: 0.0060
Epoch 66/100
72/72 [==============================] - 5s 74ms/step - loss: 0.0060
Epoch 67/100
72/72 [==============================] - 5s 76ms/step - loss: 0.0060
Epoch 68/100
72/72 [==============================] - 5s 75ms/step - loss: 0.0060
Epoch 69/100
72/72 [==============================] - 5s 76ms/step - loss: 0.0060
Epoch 70/100
72/72 [==============================] - 7s 100ms/step - loss: 0.0060
Epoch 71/100
72/72 [==============================] - 7s 99ms/step - loss: 0.0060
Epoch 72/100
72/72 [==============================] - 8s 105ms/step - loss: 0.0060
Epoch 73/100
72/72 [==============================] - 7s 93ms/step - loss: 0.0060
Epoch 74/100
72/72 [==============================] - 6s 88ms/step - loss: 0.0059
Epoch 75/100
72/72 [==============================] - 7s 101ms/step - loss: 0.0059
Epoch 76/100
72/72 [==============================] - 7s 92ms/step - loss: 0.0059
Epoch 77/100
72/72 [==============================] - 5s 75ms/step - loss: 0.0059
Epoch 78/100
72/72 [==============================] - 5s 75ms/step - loss: 0.0059
Epoch 79/100
72/72 [==============================] - 6s 80ms/step - loss: 0.0059
Epoch 80/100
72/72 [==============================] - 6s 86ms/step - loss: 0.0059
Epoch 81/100
72/72 [==============================] - 6s 80ms/step - loss: 0.0059
Epoch 82/100
72/72 [==============================] - 6s 77ms/step - loss: 0.0059
Epoch 83/100
72/72 [==============================] - 5s 76ms/step - loss: 0.0059
Epoch 84/100
72/72 [==============================] - 5s 74ms/step - loss: 0.0059
Epoch 85/100
72/72 [==============================] - 6s 78ms/step - loss: 0.0059
Epoch 86/100
72/72 [==============================] - 6s 76ms/step - loss: 0.0059
Epoch 87/100
72/72 [==============================] - 6s 82ms/step - loss: 0.0059
Epoch 88/100
72/72 [==============================] - 6s 77ms/step - loss: 0.0059
Epoch 89/100
72/72 [==============================] - 6s 86ms/step - loss: 0.0059
Epoch 90/100
72/72 [==============================] - 10s 141ms/step - loss: 0.0059
Epoch 91/100
72/72 [==============================] - 8s 117ms/step - loss: 0.0058
Epoch 92/100
72/72 [==============================] - 7s 104ms/step - loss: 0.0059
Epoch 93/100
72/72 [==============================] - 7s 101ms/step - loss: 0.0059
Epoch 94/100
72/72 [==============================] - 6s 82ms/step - loss: 0.0059
Epoch 95/100
72/72 [==============================] - 6s 85ms/step - loss: 0.0058
Epoch 96/100
72/72 [==============================] - 6s 90ms/step - loss: 0.0058
Epoch 97/100
72/72 [==============================] - 6s 77ms/step - loss: 0.0058
Epoch 98/100
72/72 [==============================] - 6s 79ms/step - loss: 0.0059
Epoch 99/100
72/72 [==============================] - 6s 83ms/step - loss: 0.0058
Epoch 100/100

72/72 [==============================] - 6s 81ms/step - loss: 0.0058

In [54]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 4)                 240

 repeat_vector (RepeatVector  (None, 20, 4)            0
 )

 lstm_1 (LSTM)               (None, 20, 100)           42000

 time_distributed (TimeDistr  (None, 20, 10)           1010
 ibuted)

=================================================================
Total params: 43,250
Trainable params: 43,250
Non-trainable params: 0
_________________________________________________________________

In [55]:
# connect the encoder LSTM as the output layer
model_feature = Model(inputs=model.inputs, outputs=model.layers[1].output)

In [56]:
model_feature.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_input (InputLayer)     [(None, 20, 10)]          0

 lstm (LSTM)                 (None, 4)                 240

 repeat_vector (RepeatVector  (None, 20, 4)            0
 )

=================================================================
Total params: 240
Trainable params: 240
Non-trainable params: 0
_________________________________________________________________

In [57]:
yhat = model_feature.predict(features_normalised)
print(yhat.shape)

72/72 [==============================] - 2s 11ms/step
(2286, 20, 4)

In [58]:
reduced_features = yhat.reshape(-1,4)

In [59]:
reduced_features.shape

(45720, 4)

In [60]:
data_with_features_covs.shape

(45720, 18)

In [61]:
final_df = data_with_features_covs.copy()
final_df.head()

,date,Open,High,Low,Close,Volume,Ticker,atr,bbw,obv,cmf,macd,adx,sma,ema,cci,rsi,cov_list
0,2013-12-03,37.950001,37.980000,37.259998,37.599998,7798700,ABT,0.569723,3.394696,196992437,0.055634,0.417395,33.540247,38.139166,37.997197,-80.958286,50.803169,"[[0.0001457882820790863, 5.427183543955608e-05..."
1,2013-12-03,76.330002,77.239998,76.029999,77.089996,2138700,ACN,1.113311,6.965746,993674137,0.042599,0.760190,27.899115,77.710000,77.143621,-5.542048,55.330879,"[[0.0001457882820790863, 5.427183543955608e-05..."
2,2013-12-03,114.440002,114.470001,112.959999,113.449997,2582300,AMGN,2.018363,4.295693,1358836137,-0.084453,-0.122541,12.489529,114.230000,114.040799,-25.742533,47.289749,"[[0.0001457882820790863, 5.427183543955608e-05..."
3,2013-12-03,84.889999,85.330002,84.199997,84.610001,3546100,AXP,1.026293,7.621025,1739265537,0.077751,1.431316,30.878730,84.051666,84.179818,78.967733,63.058139,"[[0.0001457882820790863, 5.427183543955608e-05..."
4,2013-12-03,24.635000,24.674999,24.120001,24.385000,22124600,CMCSA,0.465067,8.658425,2354191937,-0.007326,0.336446,19.818174,24.317500,24.405680,42.366350,55.607095,"[[0.0001457882820790863, 5.427183543955608e-05..."

In [62]:
final_df = final_df.drop(features_list, axis=1)

In [63]:
final_df.head()

,date,Open,High,Low,Close,Volume,Ticker,cov_list
0,2013-12-03,37.950001,37.980000,37.259998,37.599998,7798700,ABT,"[[0.0001457882820790863, 5.427183543955608e-05..."
1,2013-12-03,76.330002,77.239998,76.029999,77.089996,2138700,ACN,"[[0.0001457882820790863, 5.427183543955608e-05..."
2,2013-12-03,114.440002,114.470001,112.959999,113.449997,2582300,AMGN,"[[0.0001457882820790863, 5.427183543955608e-05..."
3,2013-12-03,84.889999,85.330002,84.199997,84.610001,3546100,AXP,"[[0.0001457882820790863, 5.427183543955608e-05..."
4,2013-12-03,24.635000,24.674999,24.120001,24.385000,22124600,CMCSA,"[[0.0001457882820790863, 5.427183543955608e-05..."

In [64]:
features_reduced_df = pd.DataFrame(reduced_features, columns=['f01','f02','f03','f04'])

In [65]:
features_reduced_df.head()

        f01  f02       f03  f04
0  0.370723  0.0  1.431267  0.0
1  0.370723  0.0  1.431267  0.0
2  0.370723  0.0  1.431267  0.0
3  0.370723  0.0  1.431267  0.0
4  0.370723  0.0  1.431267  0.0

In [66]:
final_df[['f01','f02', 'f03','f04']] = features_reduced_df[['f01','f02', 'f03','f04']]

In [67]:
final_df.head()

,date,Open,High,Low,Close,Volume,Ticker,cov_list,f01,f02,f03,f04
0,2013-12-03,37.950001,37.980000,37.259998,37.599998,7798700,ABT,"[[0.0001457882820790863, 5.427183543955608e-05...",0.370723,0.0,1.431267,0.0
1,2013-12-03,76.330002,77.239998,76.029999,77.089996,2138700,ACN,"[[0.0001457882820790863, 5.427183543955608e-05...",0.370723,0.0,1.431267,0.0
2,2013-12-03,114.440002,114.470001,112.959999,113.449997,2582300,AMGN,"[[0.0001457882820790863, 5.427183543955608e-05...",0.370723,0.0,1.431267,0.0
3,2013-12-03,84.889999,85.330002,84.199997,84.610001,3546100,AXP,"[[0.0001457882820790863, 5.427183543955608e-05...",0.370723,0.0,1.431267,0.0
4,2013-12-03,24.635000,24.674999,24.120001,24.385000,22124600,CMCSA,"[[0.0001457882820790863, 5.427183543955608e-05...",0.370723,0.0,1.431267,0.0

In [68]:
final_df.shape

(45720, 12)

In [69]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
date,,,,,,,,
2012-12-03,2012-12-03,21.201786,21.235357,20.910713,20.935356,17.951883,364280000,AAPL
2012-12-04,2012-12-04,20.778570,20.778570,20.433214,20.566071,17.635214,557068400,AAPL
2012-12-05,2012-12-05,20.318214,20.330357,19.241785,19.242500,16.500261,1044638000,AAPL
2012-12-06,2012-12-06,18.890715,19.761070,18.522499,19.544287,16.759045,1177212400,AAPL
2012-12-07,2012-12-07,19.764286,19.828571,18.928572,19.044643,16.330601,787040800,AAPL

In [70]:
df_prices = final_df.reset_index().set_index(['Ticker', 'date']).sort_index()

In [71]:
df_close = pd.DataFrame()

for ticker in filtered_stocks:
    series = df_prices.xs(ticker).Close
    df_close[ticker] = series

In [72]:
df_close.head()

,CMCSA,LIN,SO,KO,PFE,ACN,AMGN,VZ,MA,DUK,COST,USB,ABT,AXP,DHR,UPS,MCD,JNJ,TXN,V
date,,,,,,,,,,,,,,,,,,,,
2013-12-03,24.385000,124.239998,40.880001,40.349998,29.620493,77.089996,113.449997,49.599998,75.410004,69.750000,123.820000,38.520000,37.599998,84.610001,55.928734,101.900002,96.379997,93.970001,42.840000,50.437500
2013-12-04,24.440001,123.620003,41.090000,40.369999,29.667933,76.070000,113.070000,49.369999,74.817001,69.919998,122.970001,39.000000,37.360001,84.500000,55.845337,101.720001,95.709999,93.629997,42.430000,50.685001
2013-12-05,24.540001,122.489998,40.939999,39.830002,29.648956,75.790001,113.349998,48.910000,75.150002,69.599998,120.949997,38.610001,36.919998,84.540001,55.830173,101.629997,95.430000,92.970001,42.660000,50.427502
2013-12-06,24.635000,125.459999,41.430000,40.459999,29.924099,75.529999,114.120003,49.480000,75.847000,70.190002,122.059998,39.660000,37.529999,85.930000,56.952236,102.430000,96.800003,94.440002,43.490002,50.467499
2013-12-09,24.570000,125.410004,41.040001,40.400002,29.962049,75.129997,113.980003,49.570000,75.886002,69.809998,121.660004,39.740002,37.200001,85.750000,57.149357,102.339996,95.720001,94.440002,43.580002,50.397499

In [73]:
df_close.shape

(2286, 20)

In [74]:
%store df_close
%store features_reduced_df
%store final_df

Stored 'df_close' (DataFrame)
Stored 'features_reduced_df' (DataFrame)
Stored 'final_df' (DataFrame)

In [75]:
%store -r df_close
%store -r final_df
%store -r features_reduced_df

In [76]:
df_close = df_close.reset_index()

In [77]:
# Define the start and end dates for the train and test data

train_pct = 0.8 # percentage of train data
date_list = list(final_df.date.unique()) # List of dates in the data

date_list_len = len(date_list) # len of the date list
train_data_len = int(train_pct * date_list_len) # length of the train data

train_start_date = date_list[0]
train_end_date = date_list[train_data_len]

test_start_date = date_list[train_data_len+1]
test_end_date = date_list[-1]

In [78]:
print('Training Data: ', 'from ', train_start_date, ' to ', train_end_date)

Training Data:  from  2013-12-03  to  2021-03-10

In [79]:
print('Testing Data: ', 'from ', test_start_date, ' to ', test_end_date)

Testing Data:  from  2021-03-11  to  2022-12-30

In [80]:
import ta
from ta import add_all_ta_features
from ta.utils import dropna
from finrl.preprocessing.data import data_split
from finrl.preprocessing.preprocessors import FeatureEngineer

In [81]:
print(pivot_df.columns)

Index(['AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'AIG', 'AMD', 'AMGN', 'AMT',
       'AMZN', 'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY', 'C',
       'CAT', 'CHTR', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO',
       'CVS', 'CVX', 'DHR', 'DIS', 'DOW', 'DUK', 'EMR', 'EXC', 'F', 'FDX',
       'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM',
       'INTC', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LLY', 'LMT', 'LOW', 'MA',
       'MCD', 'MDLZ', 'MDT', 'MET', 'META', 'MMM', 'MO', 'MRK', 'MS', 'MSFT',
       'NEE', 'NFLX', 'NKE', 'NVDA', 'ORCL', 'PEP', 'PFE', 'PG', 'PM', 'PYPL',
       'QCOM', 'RTX', 'SBUX', 'SCHW', 'SO', 'SPG', 'T', 'TGT', 'TMO', 'TMUS',
       'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'V', 'VZ', 'WBA', 'WFC',
       'WMT', 'XOM'],
      dtype='object', name='Ticker')

In [82]:
final_df = final_df.rename(columns={'Ticker': 'tic'})

In [83]:
# Split the whole dataset
train_data = data_split(final_df, train_start_date, train_end_date)
test_data = data_split(final_df, test_start_date, test_end_date)

In [84]:
# Split the Close Prices dataset
prices_train_data = df_close[df_close['date']<=train_end_date]
prices_test_data = df_close[df_close['date']>=test_start_date]

# split the Close Prices of all stocks
prices_full_train = df_close[df_close['date']<=train_end_date]
prices_full_test = df_close[df_close['date']>=test_start_date]

In [85]:
prices_train = prices_train_data.copy()
prices_test = prices_test_data.copy()

train_df = train_data.copy()
test_df = test_data.copy()

prices_full_train_df = prices_full_train.copy()
prices_full_test_df = prices_full_test.copy()

In [87]:
prices_full_train_df

,date,CMCSA,LIN,SO,KO,PFE,ACN,AMGN,VZ,MA,...,COST,USB,ABT,AXP,DHR,UPS,MCD,JNJ,TXN,V
0,2013-12-03,24.385000,124.239998,40.880001,40.349998,29.620493,77.089996,113.449997,49.599998,75.410004,...,123.820000,38.520000,37.599998,84.610001,55.928734,101.900002,96.379997,93.970001,42.840000,50.437500
1,2013-12-04,24.440001,123.620003,41.090000,40.369999,29.667933,76.070000,113.070000,49.369999,74.817001,...,122.970001,39.000000,37.360001,84.500000,55.845337,101.720001,95.709999,93.629997,42.430000,50.685001
2,2013-12-05,24.540001,122.489998,40.939999,39.830002,29.648956,75.790001,113.349998,48.910000,75.150002,...,120.949997,38.610001,36.919998,84.540001,55.830173,101.629997,95.430000,92.970001,42.660000,50.427502
3,2013-12-06,24.635000,125.459999,41.430000,40.459999,29.924099,75.529999,114.120003,49.480000,75.847000,...,122.059998,39.660000,37.529999,85.930000,56.952236,102.430000,96.800003,94.440002,43.490002,50.467499
4,2013-12-09,24.570000,125.410004,41.040001,40.400002,29.962049,75.129997,113.980003,49.570000,75.886002,...,121.660004,39.740002,37.200001,85.750000,57.149357,102.339996,95.720001,94.440002,43.580002,50.397499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824,2021-03-04,53.930000,245.419998,57.410000,49.939999,34.200001,247.000000,221.910004,54.799999,349.500000,...,319.040009,51.020000,116.010002,142.679993,214.410004,159.449997,204.839996,153.070007,163.250000,211.500000
1825,2021-03-05,55.090000,247.639999,58.349998,50.790001,34.389999,249.509995,227.729996,56.000000,360.880005,...,317.320007,52.470001,117.250000,147.330002,218.350006,164.399994,207.369995,156.100006,167.940002,215.410004
1826,2021-03-08,55.480000,253.679993,59.610001,51.639999,34.349998,249.389999,227.809998,56.790001,371.329987,...,311.420013,54.049999,115.629997,150.270004,212.380005,160.869995,209.110001,157.399994,162.110001,220.270004
1827,2021-03-09,55.570000,262.339996,59.410000,50.860001,34.450001,254.369995,228.990005,56.200001,376.519989,...,318.779999,52.900002,116.699997,145.100006,216.339996,163.270004,208.550003,157.699997,170.360001,220.360001
1828,2021-03-10,57.209999,265.640015,59.779999,51.439999,34.930000,257.140015,229.960007,57.080002,381.700012,...,323.829987,53.779999,115.879997,146.750000,212.929993,165.229996,213.309998,159.149994,169.419998,223.169998

In [86]:
%store train_df
%store test_df
%store prices_full_train_df
%store prices_full_test_df
%store final_df

Stored 'train_df' (DataFrame)
Stored 'test_df' (DataFrame)
Stored 'prices_full_train_df' (DataFrame)
Stored 'prices_full_test_df' (DataFrame)
Stored 'final_df' (DataFrame)

# training

In [ ]:
# a2c Train Model
e_trade_gym = StockPortfolioEnv(df = train_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

a2c_train_daily_return, a2c_train_weights = DRLAgent.DRL_prediction(model=trained_a2c,
                        test_data = train_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
# PPO Train Model
e_trade_gym = StockPortfolioEnv(df = train_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

ppo_train_daily_return, ppo_train_weights = DRLAgent.DRL_prediction(model=trained_ppo,
                        test_data = train_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
# DDPG Train Model
e_trade_gym = StockPortfolioEnv(df = train_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

ddpg_train_daily_return, ddpg_train_weights = DRLAgent.DRL_prediction(model=trained_ddpg,
                        test_data = train_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
# dqn Train Model
e_trade_gym = StockPortfolioEnv(df = train_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

dqn_train_daily_return, dqn_train_weights = DRLAgent.DRL_prediction(model=trained_dqn,
                        test_data = train_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
# Store the Training Models
%store a2c_train_daily_return
%store ppo_train_daily_return
%store ddpg_train_daily_return
%store dqn_train_daily_return

In [ ]:
test_df.head(3)

In [ ]:
test_df = test_df.rename(columns={'Close': 'close'})
test_df = test_df.rename(columns={'Open': 'open'})
test_df = test_df.rename(columns={'High': 'high'})
tes_df = test_df.rename(columns={'Low': 'low'})
test_df = test_df.rename(columns={'Volume': 'volume'})

In [ ]:
# A2C Test Model
e_trade_gym = StockPortfolioEnv(df = test_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

a2c_test_daily_return, a2c_test_weights = DRLAgent.DRL_prediction(model=trained_a2c,
                        test_data = test_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
a2c_test_daily_return.head()

In [ ]:
# PPO Test Model
e_trade_gym = StockPortfolioEnv(df = test_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

ppo_test_daily_return, ppo_test_weights = DRLAgent.DRL_prediction(model=trained_ppo,
                        test_data = test_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
# DDPG Test Model
e_trade_gym = StockPortfolioEnv(df = test_df, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

ddpg_test_daily_return, ddpg_test_weights = DRLAgent.DRL_prediction(model=trained_ddpg,
                        test_data = test_df,
                        test_env = env_trade,
                        test_obs = obs_trade)

In [ ]:
a2c_test_portfolio = a2c_test_daily_return.copy()
a2c_test_returns = a2c_test_daily_return.copy()

ppo_test_portfolio = ppo_test_daily_return.copy()
ppo_test_returns = ppo_test_daily_return.copy()

ddpg_test_portfolio = ddpg_test_daily_return.copy()
ddpg_test_returns = ddpg_test_daily_return.copy()

In [ ]:
%store a2c_test_portfolio
%store a2c_test_returns 

%store ppo_test_portfolio
%store ppo_test_returns 

%store ddpg_test_portfolio
%store ddpg_test_returns

In [ ]:
%store -r max_sharpe_portfolio
%store -r uniform_weights_port

%store -r prices_train_df
%store -r prices_test_df


%store -r a2c_train_daily_return
%store -r ppo_train_daily_return
%store -r ddpg_train_daily_return

%store -r a2c_test_returns 
%store -r ppo_test_returns 
%store -r ddpg_test_returns

In [ ]:
prices_full_test_df.head()

In [ ]:
prices_full_test_df.set_index('date', inplace=True)

In [ ]:
returns_train = df.pct_change() # get the assets daily returns
returns_test = prices_full_test_df.pct_change()

# get the culmulative returns for each portfolio
uw_weights = uniform_weights_port.values.flatten()
uw_returns = returns_train.dot(uw_weights)
uw_cum_returns = (1 + uw_returns).cumprod()
uw_cum_returns.name = "portfolio 1: uniform weights"

max_sharpe_weights = max_sharpe_portfolio.values.flatten()
max_sharpe_returns = returns_train.dot(max_sharpe_weights)
max_sharpe_cum_returns = (1 + max_sharpe_returns).cumprod()
max_sharpe_cum_returns.name = "portfolio 2: max sharpe"

a2c_train_cum_returns = (1 + a2c_train_daily_return.reset_index(drop=True).set_index(['date'])).cumprod()
a2c_train_cum_returns = a2c_train_cum_returns['daily_return']
a2c_train_cum_returns.name = 'Portfolio 3: a2c Model'

ppo_train_cum_returns = (1 + ppo_train_daily_return.reset_index(drop=True).set_index(['date'])).cumprod()
ppo_train_cum_returns = ppo_train_cum_returns['daily_return']
ppo_train_cum_returns.name = 'Portfolio 4: ppo Model'

ddpg_train_cum_returns = (1 + ddpg_train_daily_return.reset_index(drop=True).set_index(['date'])).cumprod()
ddpg_train_cum_returns = ddpg_train_cum_returns['daily_return']
ddpg_train_cum_returns.name = 'Portfolio 5: ddpg Model'

date_list = list(ddpg_train_cum_returns.index)

max_sharpe_cum_returns = max_sharpe_cum_returns[(max_sharpe_cum_returns.index).isin (date_list)]
uw_cum_returns = uw_cum_returns[(uw_cum_returns.index).isin (date_list)]

In [ ]:
# Plot the culmulative returns of the portfolios
fig, ax = plt.subplots(figsize=(8,4))
uw_cum_returns.plot(ax=ax, color="black", alpha=0.4);
max_sharpe_cum_returns.plot(ax=ax, color="darkorange", alpha=0.4);

a2c_train_cum_returns.plot(ax=ax, color='blue', alpha=0.4)
ppo_train_cum_returns.plot(ax=ax, color='green', alpha=0.4)
ddpg_train_cum_returns.plot(ax=ax, color='purple', alpha=0.4)

plt.legend(loc="best");
plt.grid(True);
ax.set_ylabel("cummulative return");
ax.set_title("Backtest based on the train data", fontsize=14);
fig.savefig('results/back_test_on_train_data.png');

In [ ]:
# get the culmulative returns for each portfolio
uw_weights = uniform_weights_port.values.flatten()
uw_test_returns = returns_test.dot(uw_weights)
uw_test_cum_returns = (1 + uw_test_returns).cumprod()
uw_test_cum_returns.name = "portfolio 1: uniform weights"

max_sharpe_weights = max_sharpe_portfolio.values.flatten()
max_sharpe_test_returns = returns_test.dot(max_sharpe_weights)
max_sharpe_test_cum_returns = (1 + max_sharpe_test_returns).cumprod()
max_sharpe_test_cum_returns.name = "portfolio 2: max sharpe"

a2c_test_cum_returns = (1 + a2c_test_returns['daily_return']).cumprod()
a2c_test_cum_returns.name = 'Portfolio 3: a2c Model'

ppo_test_cum_returns = (1 + ppo_test_returns['daily_return']).cumprod()
ppo_test_cum_returns.name = 'Portfolio 4: ppo Model'

ddpg_test_cum_returns = (1 + ddpg_test_returns['daily_return']).cumprod()
ddpg_test_cum_returns.name = 'Portfolio 5: ddpg Model'

In [ ]:
# Plot the culmulative returns of the portfolios
fig, ax = plt.subplots(figsize=(8,4))
uw_test_cum_returns.plot(ax=ax, color="black", alpha=.4);
max_sharpe_test_cum_returns.plot(ax=ax, color="darkorange");
a2c_test_cum_returns.plot(ax=ax, color='blue', alpha=.4)
ppo_test_cum_returns.plot(ax=ax, color='green', alpha=.4)
ddpg_test_cum_returns.plot(ax=ax, color='purple', alpha=.4)
plt.legend(loc="best");
plt.grid(True);
ax.set_ylabel("cummulative return");
ax.set_title("Backtest based on the test data", fontsize=14);
fig.savefig('results/back_test_on_test_data.png');

In [ ]:
# Define a Function for Getting the Portfolio Statistics

def portfolio_stats(portfolio_returns):
    # Pass the returns into a dataframe
    port_rets_df = pd.DataFrame(portfolio_returns)
    port_rets_df = port_rets_df.reset_index()
    port_rets_df.columns = ['date','daily_return']
    
    #Use the FinRL Library to get the Portfolio Returns
    #This makes use of the Pyfolio Library
    
    DRL_strat = backtest_strat(port_rets_df)
    perf_func = timeseries.perf_stats 
    perf_stats_all = perf_func( returns=DRL_strat, 
                                  factor_returns=DRL_strat, 
                                    positions=None, transactions=None, turnover_denom="AGB")
    perf_stats_all = pd.DataFrame( perf_stats_all)
    perf_stats_all.columns = ['Statistic']
    return perf_stats_all

In [ ]:
uw_test_returns.shape

In [ ]:
import pyfolio.timeseries as timeseries

In [ ]:
# Get the Portfolio Statistics for all the portfolios
portfolios_returns_dict = {'uniform_weights':uw_test_returns, 'maximum_sharpe':max_sharpe_test_returns,
                          'a2c Model': a2c_test_returns['daily_return'],
                          'ppo Model': ppo_test_returns['daily_return'],
                          'ddpg Model': ddpg_test_returns['daily_return']}

portfolios_stats = pd.DataFrame()
for i,j in portfolios_returns_dict.items():
    port_stats = portfolio_stats(j)
    portfolios_stats[i] = port_stats['Statistic']

In [ ]:
portfolios_stats